apiVersion: v1
kind: Service
metadata:
  name: meetingroom-postgres
  labels:
    name: meetingroom-postgres
    project: meetingroom
spec:
  ports:
    - port: 5432
  selector:
    name: meetingroom-postgres
