apiVersion: v1
kind: PersistentVolume
metadata:
  name: meetingroom-disk
  labels:
    name: meetingroom-disk
    tier: storage
    type: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "meetingroom-disk"
    fsType: "ext4"
