# web-service.yml
apiVersion: v1
kind: Service
metadata:
  name: meetingroom-web
  labels:
    name: meetingroom-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: meetingroom-web
